baseURL = 'https://tenyoru.github.io/'
languageCode = 'en-us'
title = 'Tenyoru'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10

  [[menus.main]]
    name = 'Contact'
    pageRef = '/Contact'
    weight = 20

[security]
  enableInlineShortcodes = true
[markup.goldmark.renderer]
unsafe = true
